sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 11223344

  alioss:
    bucket-name: sky-itcast
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    endpoint: oss-cn-beijing.aliyuncs.com

  redis:
    host: localhost
    port: 6379
    password: 11223344
    database: 10

  wechat:
    appid: abcdeK
    secret: bb12ja
    mchid: "微信的商户号"
    mch-serial-no: "对应的证书序列号"
    api-v3-key: "解密的密钥"
    we-chat-pay-cert-file-path: "平台证书"
    notify-url: "支付成功的回调路径"
    refund-notify-url: "支付失败的回调路径"
    private-key-file-path: "私钥文件，一般是写路径"
  baidu:
    ak: "百度开放地图拿到的ak码"
  shop:
    address: "自己店铺的地址，在百度上显示"

